import { app, BrowserWindow, dialog, desktopCapturer, screen } from 'electron'
import { spawn, ChildProcess, execSync } from 'child_process'
import fs from 'fs'
import path from 'path'
import ffmpeg from 'fluent-ffmpeg'
import ffmpegStatic from 'ffmpeg-static'
import { IpcResponse } from '../../shared/types'
import {
  beginRecorderSelectionSession,
  canStartPreparedRecorderSelection,
  cancelRecorderSelectionSession,
  createRecorderSessionUpdate,
  clampRecorderBounds,
  ensureRecorderOutputPath,
  resolveRecorderStartSession,
  toRecorderSessionUpdate,
  type RecorderBounds,
  type RecorderSessionUpdate
} from '../../shared/screenRecorderSession'
import { processRegistry } from './ProcessRegistry'
import { createIsolatedPreloadWebPreferences } from '../utils/windowSecurity'

type ScreenRecorderConfig = {
  outputPath: string
  format: 'mp4' | 'gif'
  fps?: number
  quality?: string
  bounds?: RecorderBounds
  displayId?: string
}

type SelectionPreviewResult = {
  bounds: RecorderBounds
  displayBounds: RecorderBounds
  previewDataUrl: string
}

const INITIAL_RECORDING_TIME = '00:00:00'
const INITIAL_SESSION: RecorderSessionUpdate = {
  status: 'idle',
  mode: 'full',
  outputPath: '',
  recordingTime: INITIAL_RECORDING_TIME,
  selectionBounds: null,
  selectionPreviewDataUrl: null,
  selectedDisplayId: null
}

type CaptureDisplayBounds = RecorderBounds

type CaptureDisplayDescriptor = {
  id: number
  bounds: CaptureDisplayBounds
  scaleFactor?: number
}

type RecorderCaptureSource = {
  id: string
  name: string
  displayId: string
  thumbnail: string
  width: number
  height: number
}

const SCREEN_PICKER_THUMBNAIL_SIZE = {
  width: 320,
  height: 180
}
const BORDER_WINDOW_PADDING = 4
const AUTO_GENERATED_RECORDER_PATH_PATTERN = /OneTool-Recording-\d{8}-\d{6}-\d{3}\.(mp4|gif)$/i

function formatRecorderTimestamp(date: Date) {
  const pad = (value: number) => value.toString().padStart(2, '0')
  const milliseconds = date.getMilliseconds().toString().padStart(3, '0')
  return [
    date.getFullYear().toString(),
    pad(date.getMonth() + 1),
    pad(date.getDate())
  ].join('') + '-' + [
    pad(date.getHours()),
    pad(date.getMinutes()),
    pad(date.getSeconds())
  ].join('') + `-${milliseconds}`
}

function isAutoGeneratedRecorderPath(outputPath: string) {
  return AUTO_GENERATED_RECORDER_PATH_PATTERN.test(path.basename(outputPath))
}

function toEvenCaptureDimension(value: number) {
  const floored = Math.max(2, Math.floor(value))
  return floored % 2 === 0 ? floored : floored - 1
}

function toUnpackedAsarPath(candidatePath: string) {
  return candidatePath
    .replace(`${path.sep}app.asar${path.sep}`, `${path.sep}app.asar.unpacked${path.sep}`)
    .replace('/app.asar/', '/app.asar.unpacked/')
    .replace('\\app.asar\\', '\\app.asar.unpacked\\')
}

function toPhysicalCaptureBounds(bounds: RecorderBounds) {
  if (typeof screen.dipToScreenRect === 'function') {
    const rect = screen.dipToScreenRect(null, bounds)
    return {
      x: Math.floor(rect.x),
      y: Math.floor(rect.y),
      width: Math.floor(rect.width),
      height: Math.floor(rect.height)
    }
  }

  const topLeft = screen.dipToScreenPoint({ x: bounds.x, y: bounds.y })
  const bottomRight = screen.dipToScreenPoint({
    x: bounds.x + bounds.width,
    y: bounds.y + bounds.height
  })

  return {
    x: Math.floor(topLeft.x),
    y: Math.floor(topLeft.y),
    width: Math.floor(bottomRight.x - topLeft.x),
    height: Math.floor(bottomRight.y - topLeft.y)
  }
}

function mapRecorderSourcesToDisplays(
  displays: CaptureDisplayDescriptor[],
  sources: RecorderCaptureSource[]
): Array<{ display: CaptureDisplayDescriptor; source: RecorderCaptureSource | null }> {
  const usedSourceIndexes = new Set<number>()

  return displays.map((display) => {
    const exactMatchIndex = sources.findIndex((source, index) => {
      return !usedSourceIndexes.has(index) && source.displayId === display.id.toString()
    })

    if (exactMatchIndex >= 0) {
      usedSourceIndexes.add(exactMatchIndex)
      return { display, source: sources[exactMatchIndex] }
    }

    const fallbackIndex = sources.findIndex((_, index) => !usedSourceIndexes.has(index))
    if (fallbackIndex >= 0) {
      usedSourceIndexes.add(fallbackIndex)
      return { display, source: sources[fallbackIndex] }
    }

    return { display, source: null }
  })
}

export class ScreenRecorderService {
  private recorderProcess: ChildProcess | null = null
  private ffmpegInitialized = false
  private mainWindow: BrowserWindow | null = null
  private indicatorWindow: BrowserWindow | null = null
  private borderWindow: BrowserWindow | null = null
  private session: RecorderSessionUpdate = { ...INITIAL_SESSION }
  private borderRefreshTimer: ReturnType<typeof setTimeout> | null = null

  constructor() { }

  private buildDefaultOutputPath(format: 'mp4' | 'gif' = 'mp4') {
    const timestamp = formatRecorderTimestamp(new Date())
    return path.join(app.getPath('desktop'), `OneTool-Recording-${timestamp}.${format}`)
  }

  setMainWindow(window: BrowserWindow | null) {
    this.mainWindow = window
  }

  private getSessionSnapshot(): RecorderSessionUpdate {
    return toRecorderSessionUpdate(this.session)
  }

  private emitSessionUpdate() {
    if (this.mainWindow && !this.mainWindow.isDestroyed()) {
      this.mainWindow.webContents.send('screen-recorder-session-updated', this.getSessionSnapshot())
    }
  }

  private updateSession(
    patch: Partial<Omit<RecorderSessionUpdate, 'selectionBounds'>> & {
      selectionBounds?: RecorderBounds | null
    }
  ) {
    this.session = createRecorderSessionUpdate(this.session, patch)
    this.emitSessionUpdate()
  }

  private setSessionStatus(status: RecorderSessionUpdate['status'], recordingTime?: string) {
    this.updateSession({
      status,
      recordingTime: recordingTime ?? this.session.recordingTime
    })
  }

  getFfmpegPath(): string {
    const isDev = !app.isPackaged
    let selectedPath = ''
    const staticFfmpegPath = typeof ffmpegStatic === 'string' ? ffmpegStatic : ''
    const unpackedStaticFfmpegPath = staticFfmpegPath ? toUnpackedAsarPath(staticFfmpegPath) : ''

    if (isDev) {
      selectedPath = staticFfmpegPath
    } else {
      const possiblePaths = [
        path.join(process.resourcesPath, 'app.asar.unpacked', 'node_modules', 'ffmpeg-static', 'ffmpeg.exe'),
        path.join(process.resourcesPath, 'ffmpeg.exe'),
        path.join(process.resourcesPath, 'node_modules', 'ffmpeg-static', 'ffmpeg.exe'),
        path.join(path.dirname(app.getPath('exe')), 'resources', 'ffmpeg.exe'),
        path.join(path.dirname(app.getPath('exe')), 'ffmpeg.exe'),
        unpackedStaticFfmpegPath,
        staticFfmpegPath
      ]

      for (const testPath of possiblePaths) {
        if (testPath && fs.existsSync(testPath)) {
          selectedPath = testPath
          break
        }
      }
    }

    if (!selectedPath) selectedPath = isDev ? staticFfmpegPath : unpackedStaticFfmpegPath || staticFfmpegPath

    try {
      execSync(`"${selectedPath}" -version`, { stdio: 'ignore', timeout: 2000 })
    } catch (e) {
      console.warn('ScreenRecorderService: FFmpeg path validation warning:', selectedPath)
    }

    return selectedPath
  }

  initFfmpeg() {
    if (this.ffmpegInitialized) return

    const ffmpegPath = this.getFfmpegPath()
    if (ffmpegPath && fs.existsSync(ffmpegPath)) {
      ffmpeg.setFfmpegPath(ffmpegPath)
      this.ffmpegInitialized = true
    } else {
      console.error('ScreenRecorderService: Failed to initialize FFmpeg')
    }
  }

  private createIndicatorWindow(bounds: RecorderBounds) {
    const { x, y, width } = bounds
    const windowBounds = {
      width: 260,
      height: 48,
      x: Math.round(x + width / 2 - 130),
      y: y + 10
    }

    if (this.indicatorWindow && !this.indicatorWindow.isDestroyed()) {
      this.indicatorWindow.setBounds(windowBounds)
      this.indicatorWindow.show?.()
      return
    }

    this.indicatorWindow = new BrowserWindow({
      ...windowBounds,
      type: 'toolbar',
      frame: false,
      transparent: true,
      hasShadow: false,
      alwaysOnTop: true,
      resizable: false,
      skipTaskbar: true,
      show: false,
      webPreferences: createIsolatedPreloadWebPreferences(path.join(__dirname, '../preload/index.js'))
    })

    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <style>
          body { margin: 0; overflow: hidden; background: transparent; font-family: "Microsoft YaHei", "Segoe UI", sans-serif; }
          .container {
            display: flex;
            align-items: center;
            gap: 10px;
            padding: 8px 10px;
            margin: 0 auto;
            width: fit-content;
            color: white;
            background: rgba(12, 12, 12, 0.86);
            border: 1px solid rgba(255, 255, 255, 0.12);
            border-radius: 999px;
            box-shadow: 0 8px 24px rgba(0, 0, 0, 0.35);
            -webkit-app-region: drag;
          }
          .dot { width: 10px; height: 10px; border-radius: 50%; background: #ef4444; animation: pulse 1s infinite alternate; }
          .time { min-width: 64px; font-family: Consolas, monospace; font-size: 12px; }
          .button {
            border: none;
            border-radius: 999px;
            padding: 6px 10px;
            font-size: 12px;
            color: white;
            cursor: pointer;
            -webkit-app-region: no-drag;
          }
          .button.secondary { background: rgba(255, 255, 255, 0.12); }
          .button.danger { background: #dc2626; }
          @keyframes pulse { 0% { opacity: 0.45; } 100% { opacity: 1; box-shadow: 0 0 8px rgba(239, 68, 68, 0.6); } }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="dot"></div>
          <div>正在录制</div>
          <div class="time" id="time">00:00:00</div>
          <button class="button danger" id="stop">停止</button>
        </div>
        <script>
          const timeNode = document.getElementById('time');
          document.getElementById('stop').addEventListener('click', () => {
            window.electron.screenRecorder.stopRecording();
          });
          window.electron.screenRecorder.onIndicatorTimeUpdated((time) => {
            timeNode.innerText = time;
          });
        </script>
      </body>
      </html>
    `

    this.indicatorWindow.loadURL(`data:text/html;charset=utf-8,${encodeURIComponent(htmlContent)}`)
    this.indicatorWindow.setVisibleOnAllWorkspaces(true, { visibleOnFullScreen: true })
    this.indicatorWindow.setIgnoreMouseEvents(false)
    this.indicatorWindow.setContentProtection(true)
    this.indicatorWindow.show?.()
  }

  getPreparedSelectionBounds(): RecorderBounds | null {
    return this.session.selectionBounds ? { ...this.session.selectionBounds } : null
  }

  private getBorderWindowBounds(bounds: RecorderBounds) {
    return {
      x: bounds.x - BORDER_WINDOW_PADDING,
      y: bounds.y - BORDER_WINDOW_PADDING,
      width: bounds.width + BORDER_WINDOW_PADDING * 2,
      height: bounds.height + BORDER_WINDOW_PADDING * 2
    }
  }

  private createBorderWindow(bounds: RecorderBounds, interactive = true) {
    const windowBounds = this.getBorderWindowBounds(bounds)
    if (this.borderWindow && !this.borderWindow.isDestroyed()) {
      this.borderWindow.setBounds(windowBounds)
      if (interactive) {
        this.borderWindow.setIgnoreMouseEvents(false)
      } else {
        this.borderWindow.setIgnoreMouseEvents(true, { forward: true })
      }
      this.borderWindow.show?.()
      return
    }

    this.borderWindow = new BrowserWindow({
      ...windowBounds,
      type: 'toolbar',
      frame: false,
      transparent: true,
      hasShadow: false,
      alwaysOnTop: true,
      resizable: false,
      skipTaskbar: true,
      show: false,
      webPreferences: createIsolatedPreloadWebPreferences(path.join(__dirname, '../preload/index.js'))
    })

    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <style>
          body {
            margin: 0;
            overflow: hidden;
            background: transparent;
            width: 100vw;
            height: 100vh;
            cursor: move;
            user-select: none;
          }
          #drag-surface {
            position: absolute;
            inset: 0;
            cursor: move;
          }
          .border-box {
            position: absolute;
            inset: 0;
            border: 4px dashed #ef4444;
            box-sizing: border-box;
            background: transparent;
            animation: border-flash 1s infinite alternate;
          }
          @keyframes border-flash { 0% { border-color: rgba(239, 68, 68, 0.4); } 100% { border-color: rgba(239, 68, 68, 1); } }
        </style>
      </head>
      <body>
        <div id="drag-surface">
          <div class="border-box"></div>
        </div>
        <script>
          const dragSurface = document.getElementById('drag-surface');
          let dragging = false;
          let lastScreenX = 0;
          let lastScreenY = 0;
          let queuedDeltaX = 0;
          let queuedDeltaY = 0;
          let rafPending = false;

          const flushQueuedMove = () => {
            rafPending = false;
            if (queuedDeltaX === 0 && queuedDeltaY === 0) {
              return;
            }

            window.electron.screenRecorder.moveSelectionBy(queuedDeltaX, queuedDeltaY);
            queuedDeltaX = 0;
            queuedDeltaY = 0;
          };

          const stopDragging = (pointerId) => {
            if (!dragging) {
              return;
            }

            dragging = false;
            if (typeof pointerId === 'number' && dragSurface.hasPointerCapture?.(pointerId)) {
              dragSurface.releasePointerCapture(pointerId);
            }
            flushQueuedMove();
          };

          dragSurface.addEventListener('pointerdown', (event) => {
            dragging = true;
            lastScreenX = event.screenX;
            lastScreenY = event.screenY;
            dragSurface.setPointerCapture?.(event.pointerId);
            event.preventDefault();
          });

          dragSurface.addEventListener('pointermove', (event) => {
            if (!dragging) {
              return;
            }

            const deltaX = event.screenX - lastScreenX;
            const deltaY = event.screenY - lastScreenY;
            lastScreenX = event.screenX;
            lastScreenY = event.screenY;

            if (deltaX === 0 && deltaY === 0) {
              return;
            }

            queuedDeltaX += deltaX;
            queuedDeltaY += deltaY;
            if (!rafPending) {
              rafPending = true;
              requestAnimationFrame(flushQueuedMove);
            }
          });

          dragSurface.addEventListener('pointerup', (event) => {
            stopDragging(event.pointerId);
          });
          dragSurface.addEventListener('pointercancel', (event) => {
            stopDragging(event.pointerId);
          });
          window.addEventListener('blur', () => {
            stopDragging();
          });
        </script>
      </body>
      </html>
    `

    this.borderWindow.loadURL(`data:text/html;charset=utf-8,${encodeURIComponent(htmlContent)}`)
    if (interactive) {
      this.borderWindow.setIgnoreMouseEvents(false)
    } else {
      this.borderWindow.setIgnoreMouseEvents(true, { forward: true })
    }
    this.borderWindow.setVisibleOnAllWorkspaces(true, { visibleOnFullScreen: true })
    this.borderWindow.setContentProtection(true)
    this.borderWindow.show?.()
  }

  private destroyBorderWindow() {
    if (this.borderRefreshTimer) {
      clearTimeout(this.borderRefreshTimer)
      this.borderRefreshTimer = null
    }

    if (this.borderWindow) {
      if (!this.borderWindow.isDestroyed()) {
        this.borderWindow.close()
      }
      this.borderWindow = null
    }
  }

  hideSelectionPreview() {
    if (this.borderRefreshTimer) {
      clearTimeout(this.borderRefreshTimer)
      this.borderRefreshTimer = null
    }

    if (this.borderWindow && !this.borderWindow.isDestroyed()) {
      this.borderWindow.hide?.()
    }
  }

  private scheduleBorderPreview(bounds: RecorderBounds, interactive = true) {
    if (this.borderRefreshTimer) {
      clearTimeout(this.borderRefreshTimer)
    }

    this.borderRefreshTimer = setTimeout(() => {
      this.borderRefreshTimer = null
      this.createBorderWindow(bounds, interactive)
    }, 0)
  }

  private destroyIndicatorWindow() {
    if (this.indicatorWindow) {
      if (!this.indicatorWindow.isDestroyed()) {
        this.indicatorWindow.hide?.()
      }
    }

    this.hideSelectionPreview()
  }

  private getIndicatorBounds(config: ScreenRecorderConfig): RecorderBounds {
    if (this.session.mode === 'area' && this.session.selectionBounds) {
      return this.session.selectionBounds
    }

    if (config.displayId) {
      const matchedDisplay = screen.getAllDisplays().find((display) => display.id.toString() === config.displayId)
      if (matchedDisplay) {
        return matchedDisplay.bounds
      }
    }

    return screen.getPrimaryDisplay().bounds
  }

  private buildCaptureArgs(config: ScreenRecorderConfig): string[] {
    const primaryDisplay = screen.getPrimaryDisplay()
    const fps = config.fps || 30
    const args = ['-y', '-f', 'gdigrab', '-framerate', fps.toString()]
    const areaBounds = this.session.mode === 'area' ? this.session.selectionBounds : null

    if (areaBounds) {
      const physicalBounds = toPhysicalCaptureBounds(areaBounds)
      let realX = physicalBounds.x
      let realY = physicalBounds.y
      const realW = toEvenCaptureDimension(physicalBounds.width)
      const realH = toEvenCaptureDimension(physicalBounds.height)

      args.push(
        '-offset_x', realX.toString(),
        '-offset_y', realY.toString(),
        '-video_size', `${realW}x${realH}`,
        '-i', 'desktop'
      )

      return args
    }

    if (config.displayId) {
      const display = screen.getAllDisplays().find((item) => item.id.toString() === config.displayId) || primaryDisplay
      const physicalBounds = toPhysicalCaptureBounds(display.bounds)
      let realX = physicalBounds.x
      let realY = physicalBounds.y
      const realW = toEvenCaptureDimension(physicalBounds.width)
      const realH = toEvenCaptureDimension(physicalBounds.height)

      args.push(
        '-offset_x', realX.toString(),
        '-offset_y', realY.toString(),
        '-video_size', `${realW}x${realH}`,
        '-i', 'desktop'
      )

      return args
    }

    const physicalBounds = toPhysicalCaptureBounds(primaryDisplay.bounds)
    const realW = toEvenCaptureDimension(physicalBounds.width)
    const realH = toEvenCaptureDimension(physicalBounds.height)

    args.push(
      '-offset_x', physicalBounds.x.toString(),
      '-offset_y', physicalBounds.y.toString(),
      '-video_size', `${realW}x${realH}`,
      '-i', 'desktop'
    )

    return args
  }

  private bindRecorderProcess(config: ScreenRecorderConfig) {
    if (!this.recorderProcess || !this.recorderProcess.stderr) {
      return
    }

    const recentStderr: string[] = []

    this.recorderProcess.stderr.on('data', (data) => {
      const msg = data.toString()
      const stderrLines = msg
        .split(/\r?\n/)
        .map((line) => line.trim())
        .filter(Boolean)
      if (stderrLines.length > 0) {
        recentStderr.push(...stderrLines)
        if (recentStderr.length > 8) {
          recentStderr.splice(0, recentStderr.length - 8)
        }
      }

      const timeMatch = msg.match(/time=(\d{2}:\d{2}:\d{2})/)
      if (!timeMatch) {
        return
      }

      const recordingTime = timeMatch[1]
      this.updateSession({ recordingTime })

      if (this.mainWindow && !this.mainWindow.isDestroyed()) {
        this.mainWindow.webContents.send('screen-recorder-progress', { timemark: recordingTime })
      }

      if (this.indicatorWindow && !this.indicatorWindow.isDestroyed()) {
        this.indicatorWindow.webContents.send('update-time', recordingTime)
      }
    })

    this.recorderProcess.on('error', (err) => {
      this.recorderProcess = null
      this.destroyIndicatorWindow()
      this.updateSession({ status: 'idle', recordingTime: INITIAL_RECORDING_TIME })

      if (this.mainWindow && !this.mainWindow.isDestroyed()) {
        this.mainWindow.webContents.send('screen-recorder-stopped', { success: false, error: err.message })
      }
    })

    this.recorderProcess.on('close', (code) => {
      const wasGracefulStop = this.session.status === 'finishing'
      const wasRecording = this.session.status === 'recording' || wasGracefulStop

      if (wasRecording && !wasGracefulStop && this.mainWindow && !this.mainWindow.isDestroyed()) {
        console.error('ScreenRecorderService: FFmpeg exited unexpectedly', {
          code,
          args: this.buildCaptureArgs(config),
          stderr: recentStderr
        })
        this.mainWindow.webContents.send('app-notification', {
          type: 'error',
          title: '录制异常中断',
          message: recentStderr.length > 0
            ? `FFmpeg 进程意外退出 (错误码: ${code})，录制已停止。${recentStderr.at(-1)}`
            : `FFmpeg 进程意外退出 (错误码: ${code})，录制已停止。`,
          duration: 5000
        })
      }

      this.recorderProcess = null
      this.destroyIndicatorWindow()
      const nextOutputPath =
        isAutoGeneratedRecorderPath(this.session.outputPath)
          ? this.buildDefaultOutputPath(config.format)
          : this.session.outputPath
      this.updateSession({
        status: 'idle',
        recordingTime: INITIAL_RECORDING_TIME,
        outputPath: nextOutputPath
      })

      if (this.mainWindow && !this.mainWindow.isDestroyed()) {
        this.mainWindow.show()
        const success = wasGracefulStop ? (code === 0 || code === 1 || code === null) : code === 0
        this.mainWindow.webContents.send('screen-recorder-stopped', {
          success,
          outputPath: config.outputPath
        })
      }
    })
  }

  async selectOutput(
    window: BrowserWindow | null,
    format: 'mp4' | 'gif' = 'mp4'
  ): Promise<IpcResponse<{ canceled: boolean, filePath: string | null }>> {
    try {
      if (!window) return { success: false, error: '窗口不存在' }

      const { canceled, filePath } = await dialog.showSaveDialog(window, {
        title: '选择保存位置',
        filters: [
          { name: 'MP4 视频', extensions: ['mp4'] },
          { name: 'GIF 动画', extensions: ['gif'] }
        ],
        defaultPath: this.buildDefaultOutputPath(format)
      })

      return { success: true, data: { canceled, filePath: !canceled ? filePath : null } }
    } catch (error) {
      return { success: false, error: (error as Error).message }
    }
  }

  async getScreens(): Promise<IpcResponse<any[]>> {
    try {
      const displays = screen.getAllDisplays()
      const sources = await desktopCapturer.getSources({
        types: ['screen'],
        thumbnailSize: SCREEN_PICKER_THUMBNAIL_SIZE
      })

      const normalizedSources: RecorderCaptureSource[] = sources.map((source) => {
        const size = source.thumbnail.getSize()
        return {
          id: source.id,
          name: source.name,
          displayId: source.display_id?.trim() || '',
          thumbnail: source.thumbnail.toDataURL(),
          width: size.width,
          height: size.height
        }
      })

      const mappedDisplays = mapRecorderSourcesToDisplays(displays, normalizedSources)
      return {
        success: true,
        data: mappedDisplays
          .filter((entry) => entry.source)
          .map((entry, index) => ({
            id: entry.source!.id,
            name: entry.source!.name || `屏幕 ${index + 1}`,
            display_id: entry.display.id.toString(),
            thumbnail: entry.source!.thumbnail
          }))
      }
    } catch (e) {
      return { success: false, error: (e as Error).message }
    }
  }

  beginSelection() {
    const nextSession = beginRecorderSelectionSession(this.session)
    if (!nextSession) {
      return false
    }

    this.hideSelectionPreview()
    this.session = nextSession
    this.emitSessionUpdate()
    return true
  }

  cancelSelection() {
    if (this.session.status !== 'selecting-area') {
      return false
    }

    this.session = cancelRecorderSelectionSession(this.session)
    if (this.session.mode === 'area' && this.session.status === 'ready-to-record' && this.session.selectionBounds) {
      this.createBorderWindow(this.session.selectionBounds)
    } else {
      this.hideSelectionPreview()
    }
    this.emitSessionUpdate()
    return true
  }

  async prepareSelection(bounds: RecorderBounds): Promise<IpcResponse<SelectionPreviewResult>> {
    try {
      if (this.recorderProcess || this.session.status === 'recording' || this.session.status === 'finishing') {
        return { success: false, error: '录制进行中，无法准备选区' }
      }

      const targetDisplay = screen.getDisplayNearestPoint({
        x: bounds.x + bounds.width / 2,
        y: bounds.y + bounds.height / 2
      })

      const clampedBounds = clampRecorderBounds(bounds, targetDisplay.bounds)

      this.updateSession(
        toRecorderSessionUpdate({
          status: 'ready-to-record',
          mode: 'area',
          outputPath: this.session.outputPath,
          recordingTime: INITIAL_RECORDING_TIME,
          selectionBounds: clampedBounds,
          selectionPreviewDataUrl: null,
          selectedDisplayId: targetDisplay.id.toString()
        })
      )
      this.scheduleBorderPreview(clampedBounds)

      return {
        success: true,
        data: {
          bounds: clampedBounds,
          displayBounds: { ...targetDisplay.bounds },
          previewDataUrl: ''
        }
      }
    } catch (error) {
      return { success: false, error: (error as Error).message }
    }
  }

  movePreparedSelectionBy(deltaX: number, deltaY: number): IpcResponse<{ bounds: RecorderBounds }> {
    try {
      if (this.session.status !== 'ready-to-record' || this.session.mode !== 'area' || !this.session.selectionBounds) {
        return { success: false, error: '当前没有可移动的录制选区' }
      }

      if (!Number.isFinite(deltaX) || !Number.isFinite(deltaY)) {
        return { success: false, error: '无效的选区偏移量' }
      }

      const availableDisplay =
        screen.getAllDisplays().find((display) => display.id.toString() === this.session.selectedDisplayId) ??
        screen.getDisplayNearestPoint({
          x: this.session.selectionBounds.x + this.session.selectionBounds.width / 2,
          y: this.session.selectionBounds.y + this.session.selectionBounds.height / 2
        })

      const nextBounds = clampRecorderBounds(
        {
          x: this.session.selectionBounds.x + Math.round(deltaX),
          y: this.session.selectionBounds.y + Math.round(deltaY),
          width: this.session.selectionBounds.width,
          height: this.session.selectionBounds.height
        },
        availableDisplay.bounds
      )

      this.updateSession({
        selectionBounds: nextBounds,
        selectedDisplayId: availableDisplay.id.toString()
      })
      this.createBorderWindow(nextBounds)

      return { success: true, data: { bounds: nextBounds } }
    } catch (error) {
      return { success: false, error: (error as Error).message }
    }
  }

  expandPanel(): IpcResponse {
    try {
      if (this.session.status === 'recording' || this.session.status === 'finishing') {
        return { success: false, error: '录制中无法展开主面板' }
      }

      if (this.mainWindow && !this.mainWindow.isDestroyed()) {
        if (this.mainWindow.isMinimized()) {
          this.mainWindow.restore()
        }
        this.mainWindow.show()
        this.mainWindow.focus()
      }

      return { success: true }
    } catch (error) {
      return { success: false, error: (error as Error).message }
    }
  }

  async start(config: ScreenRecorderConfig): Promise<IpcResponse> {
    try {
      if (this.recorderProcess || this.session.status === 'recording' || this.session.status === 'finishing') {
        return { success: false, error: '录制已在进行中' }
      }

      const ffmpegPath = this.getFfmpegPath()
      if (!ffmpegPath || !fs.existsSync(ffmpegPath)) {
        return { success: false, error: 'FFmpeg 未正确安装或路径无效' }
      }

      const requestedOutputPath = ensureRecorderOutputPath(config.outputPath, config.format === 'gif' ? 'gif' : 'mp4')
      const normalizedOutputPath = isAutoGeneratedRecorderPath(requestedOutputPath)
        ? this.buildDefaultOutputPath(config.format === 'gif' ? 'gif' : 'mp4')
        : requestedOutputPath
      const sessionUpdate = resolveRecorderStartSession(this.session, {
        outputPath: normalizedOutputPath,
        displayId: config.displayId,
        usePreparedSelection: Boolean(config.bounds)
      })
      if (sessionUpdate === null) {
        return { success: false, error: '请先完成录制区域确认' }
      }

      this.session = sessionUpdate
      this.emitSessionUpdate()

      if (this.mainWindow && !this.mainWindow.isDestroyed()) {
        this.mainWindow.minimize()
      }

      const args = this.buildCaptureArgs({
        ...config,
        outputPath: normalizedOutputPath
      })

      args.push('-draw_mouse', '1')

      if (config.format === 'mp4') {
        const crf = config.quality === 'high' ? '23' : config.quality === 'medium' ? '28' : '32'
        args.push(
          '-c:v', 'libx264',
          '-preset', 'ultrafast',
          '-crf', crf,
          '-pix_fmt', 'yuv420p',
          '-tune', 'zerolatency',
          '-movflags', '+faststart',
          '-vf', 'scale=trunc(iw/2)*2:trunc(ih/2)*2',
          normalizedOutputPath
        )
      } else if (config.format === 'gif') {
        args.push(
          '-f', 'gif',
          '-vf', 'fps=10,scale=trunc(iw/2)*2:trunc(ih/2)*2',
          normalizedOutputPath
        )
      }

      this.recorderProcess = spawn(ffmpegPath, args, { stdio: ['pipe', 'pipe', 'pipe'] })
      processRegistry.register(this.recorderProcess)

      if (!this.recorderProcess || !this.recorderProcess.stdin || !this.recorderProcess.stderr) {
        this.recorderProcess = null
        this.updateSession({ status: 'idle', recordingTime: INITIAL_RECORDING_TIME })
        return { success: false, error: '无法启动录制进程' }
      }

      this.bindRecorderProcess({ ...config, outputPath: normalizedOutputPath })

      if (this.mainWindow && !this.mainWindow.isDestroyed()) {
        this.mainWindow.webContents.send('screen-recorder-started')
      }

      const indicatorBounds = this.getIndicatorBounds({ ...config, outputPath: normalizedOutputPath })
      this.createIndicatorWindow(indicatorBounds)
      if (this.session.mode === 'area' && this.session.selectionBounds) {
        this.createBorderWindow(this.session.selectionBounds, false)
      }

      return { success: true }
    } catch (error) {
      this.recorderProcess = null
      this.destroyIndicatorWindow()
      this.updateSession({ status: 'idle', recordingTime: INITIAL_RECORDING_TIME })
      return { success: false, error: (error as Error).message }
    }
  }

  async stop(): Promise<IpcResponse> {
    try {
      if (!this.recorderProcess || this.session.status !== 'recording') {
        return { success: false, error: '没有正在进行的录制' }
      }

      this.setSessionStatus('finishing')

      if (this.recorderProcess.stdin && this.recorderProcess.stdin.writable) {
        const processToKill = this.recorderProcess
        this.recorderProcess.stdin.write('q')
        setTimeout(() => {
          if (this.recorderProcess === processToKill && this.session.status === 'finishing') {
            processToKill.kill('SIGKILL')
          }
        }, 5000)
      } else {
        this.recorderProcess.kill('SIGINT')
      }

      return { success: true }
    } catch (error) {
      return { success: false, error: (error as Error).message }
    }
  }

  getStatus(): IpcResponse<{ recording: boolean }> {
    return {
      success: true,
      data: { recording: this.session.status === 'recording' || this.session.status === 'finishing' }
    }
  }

  getSession(): IpcResponse<RecorderSessionUpdate> {
    return {
      success: true,
      data: this.getSessionSnapshot()
    }
  }

  getDefaultPath(format: 'mp4' | 'gif' = 'mp4'): IpcResponse<string> {
    return { success: true, data: this.buildDefaultOutputPath(format) }
  }
}

export const screenRecorderService = new ScreenRecorderService()
