export const DEFAULT_EVENTS = [
  {
    id: "seed-team-sync-mon",
    title: "团队会议",
    date: "2025-07-21",
    start: "09:00",
    end: "10:00",
    calendar: "工作",
    color: "#4fc39b",
    location: "湖景会议室 A",
    participants: "林澈、沈以南、顾清禾",
    description: "同步本周交付节奏，确认设计与工程之间的阻塞项。"
  },
  {
    id: "seed-lunch-mon",
    title: "午餐约会",
    date: "2025-07-21",
    start: "12:00",
    end: "13:00",
    calendar: "重要",
    color: "#c98b2f",
    location: "松影餐厅靠窗位",
    participants: "韩叙",
    description: "讨论客户提案的叙事结构，顺便把下一版材料的负责人定下来。"
  },
  {
    id: "seed-client-call",
    title: "客户电话",
    date: "2025-07-21",
    start: "14:00",
    end: "15:00",
    calendar: "工作",
    color: "#7658d8",
    location: "远程会议",
    participants: "北辰资本、莫雨笙",
    description: "确认预算边界和上线窗口，整理会后纪要给产品团队。"
  },
  {
    id: "seed-progress-tue",
    title: "项目进度",
    date: "2025-07-22",
    start: "10:00",
    end: "11:00",
    calendar: "工作",
    color: "#b84686",
    location: "项目作战室",
    participants: "研发小组",
    description: "检查里程碑完成度，提前识别需要调整排期的任务。"
  },
  {
    id: "seed-design-review",
    title: "设计评审",
    date: "2025-07-22",
    start: "13:00",
    end: "14:00",
    calendar: "工作",
    color: "#38a9bd",
    location: "设计室",
    participants: "许棠、周岚、产品策略组",
    description: "评审新版信息架构，重点看移动端阅读密度和事件卡层级。"
  },
  {
    id: "seed-workout",
    title: "健身",
    date: "2025-07-22",
    start: "15:00",
    end: "16:00",
    calendar: "个人",
    color: "#bb3e43",
    location: "山谷健身房",
    participants: "个人",
    description: "力量训练与拉伸，保持下午状态稳定。"
  },
  {
    id: "seed-standup",
    title: "早会",
    date: "2025-07-23",
    start: "08:00",
    end: "09:00",
    calendar: "工作",
    color: "#75aa3b",
    location: "主会议室",
    participants: "全体成员",
    description: "快速同步今日优先级，避免上午被零碎沟通切散。"
  },
  {
    id: "seed-team-sync-wed",
    title: "团队会议",
    date: "2025-07-23",
    start: "11:00",
    end: "12:00",
    calendar: "工作",
    color: "#319777",
    location: "湖景会议室 B",
    participants: "林澈、沈以南、陈闻溪",
    description: "确认跨部门资源安排，并把决策记录到项目空间。"
  },
  {
    id: "seed-training",
    title: "培训",
    date: "2025-07-23",
    start: "14:00",
    end: "15:00",
    calendar: "工作",
    color: "#5867c7",
    location: "培训室",
    participants: "运营与客服团队",
    description: "新工具培训，覆盖搜索、批量编辑和提醒策略。"
  },
  {
    id: "seed-client-meeting",
    title: "客户会议",
    date: "2025-07-23",
    start: "16:00",
    end: "17:00",
    calendar: "工作",
    color: "#6d4ec2",
    location: "客户办公室",
    participants: "蓝岭影像、交付团队",
    description: "演示当前版本，收集客户对视觉方向和交互流程的反馈。"
  },
  {
    id: "seed-planning",
    title: "规划会议",
    date: "2025-07-24",
    start: "09:00",
    end: "10:00",
    calendar: "重要",
    color: "#c0822c",
    location: "北侧圆桌区",
    participants: "产品委员会",
    description: "确定八月主题和发布节奏，给每条工作线设定清晰出口。"
  },
  {
    id: "seed-team-building",
    title: "团队建设",
    date: "2025-07-24",
    start: "14:00",
    end: "15:00",
    calendar: "家庭",
    color: "#b74a86",
    location: "露台休息区",
    participants: "核心项目组",
    description: "轻量复盘团队协作方式，沉淀下一阶段的协作约定。"
  },
  {
    id: "seed-report",
    title: "进度报告",
    date: "2025-07-25",
    start: "10:00",
    end: "11:00",
    calendar: "工作",
    color: "#2d9ab1",
    location: "线上会议",
    participants: "管理层",
    description: "汇报关键指标、风险和需要管理层拍板的事项。"
  },
  {
    id: "seed-lunch-fri",
    title: "午餐",
    date: "2025-07-25",
    start: "12:00",
    end: "13:00",
    calendar: "个人",
    color: "#c74d52",
    location: "杉林食堂",
    participants: "个人",
    description: "留出完整午餐时间，避免连续会议造成能量断层。"
  },
  {
    id: "seed-weekend-plan",
    title: "周末计划",
    date: "2025-07-25",
    start: "15:00",
    end: "16:00",
    calendar: "个人",
    color: "#70a72e",
    location: "移动端",
    participants: "个人",
    description: "安排周末采购、徒步和家庭聚会准备事项。"
  },
  {
    id: "seed-family-lunch",
    title: "午餐约会",
    date: "2025-07-26",
    start: "12:00",
    end: "13:00",
    calendar: "家庭",
    color: "#626bd4",
    location: "白石咖啡",
    participants: "苏晚晴",
    description: "轻松午餐，讨论周末家庭安排。"
  },
  {
    id: "seed-family-dinner",
    title: "家庭聚餐",
    date: "2025-07-27",
    start: "14:00",
    end: "15:00",
    calendar: "家庭",
    color: "#35a47f",
    location: "家中餐厅",
    participants: "家人",
    description: "准备晚些时候的家庭聚餐，把采购和布置提前安排好。"
  }
];
