const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

test('FileDropover uses a dedicated float-ball icon asset', () => {
  const filePath = path.join(__dirname, 'FileDropover.tsx')
  const source = fs.readFileSync(filePath, 'utf8')

  assert.match(source, /import floatBallIcon from '@\/assets\/floatball-icon\.png'/)
  assert.doesNotMatch(source, /import appIcon from '\.\.\/\.\.\/\.\.\/\.\.\/resources\/icon\.png'/)
})

test('FileDropover uses the brighter float-ball shell styling', () => {
  const filePath = path.join(__dirname, 'FileDropover.tsx')
  const source = fs.readFileSync(filePath, 'utf8')

  assert.match(source, /useState\(\{ width: 96, height: 96 \}\)/)
  assert.match(source, /setWindowSize\(\{ width: 96, height: 96 \}\)/)
  assert.match(source, /h-\[96px\] w-\[96px\]/)
  assert.match(source, /origin-\[48px_48px\]/)
  assert.match(source, /h-\[40px\]/)
  assert.match(source, /w-\[40px\]/)
  assert.match(source, /tabular-nums/)
  assert.match(source, /grid-cols-\[15px_1fr\]/)
  assert.match(source, /group\/trigger/)
  assert.match(source, /CPU/)
  assert.match(source, /MEM/)
  assert.match(source, /transition-\[width\]/)
  assert.match(source, /group-hover\/trigger:scale-\[1\.04\]/)
  assert.match(source, /group-hover\/trigger:-translate-y-\[1px\]/)
  assert.doesNotMatch(source, /mix-blend-screen/)
  assert.doesNotMatch(source, /bg-white\/16/)
  assert.doesNotMatch(source, /bg-white\/24/)
  assert.doesNotMatch(source, /rgba\(\s*127,\s*86,\s*217,\s*0\.55\s*\)/)
})

test('FileDropover derives dock side from endDrag result and exposes a renderer peek state path', () => {
  const filePath = path.join(__dirname, 'FileDropover.tsx')
  const source = fs.readFileSync(filePath, 'utf8')

  assert.match(source, /dockState/)
  assert.match(source, /'free' \| 'docked' \| 'peek' \| 'dragging'/)
  assert.match(source, /docked-left/)
  assert.match(source, /docked-right/)
  assert.match(source, /peek/)
  assert.match(source, /beginDrag\(\{ pointerOffsetX:/)
  assert.match(source, /electron\.floatBall\.dragTo\(/)
  assert.match(source, /pendingDragPositionRef/)
  assert.match(source, /requestAnimationFrame/)
  assert.match(source, /cancelAnimationFrame/)
  assert.match(source, /dockEdgeOffsetClass/)
  assert.match(source, /-translate-x-\[8px\]/)
  assert.match(source, /translate-x-\[8px\]/)
  assert.match(source, /transition-none duration-0/)
  assert.match(source, /const result = await electron\.floatBall\.endDrag\(\)/)
  assert.match(source, /result\?\.data\?\.dockState === 'docked' \? 'docked' : 'free'/)
  assert.match(source, /result\?\.data\?\.dockSide\s*===\s*'left'/)
  assert.match(source, /result\?\.data\?\.dockSide\s*===\s*'right'/)
  assert.match(source, /'docked-left'/)
  assert.match(source, /'docked-right'/)
  assert.match(source, /setDockState\('peek'\)/)
  assert.match(source, /onMouseEnter=/)
  assert.match(source, /onMouseLeave=/)
  assert.match(source, /onDoubleClick=/)
  assert.match(source, /onContextMenu=/)
  assert.match(source, /CPU/)
  assert.match(source, /MEM/)
  assert.match(source, /dockSide === 'docked-left' \? 'justify-start' : 'justify-end'/)
  assert.doesNotMatch(source, /floatBall\.setPosition\(/)
})

test('FileDropover clears dragging state even when endDrag fails', () => {
  const filePath = path.join(__dirname, 'FileDropover.tsx')
  const source = fs.readFileSync(filePath, 'utf8')

  assert.match(source, /try \{/)
  assert.match(source, /await electron\.floatBall\.endDrag\(\)/)
  assert.match(source, /catch \(err\)/)
  assert.match(source, /let nextDockState: 'free' \| 'docked' = 'free'/)
  assert.match(source, /setDockState\(nextDockState\)/)
  assert.match(source, /finally \{/)
})

test('FileDropover renders animated status shell with realtime stats', () => {
  const filePath = path.join(__dirname, 'FileDropover.tsx')
  const source = fs.readFileSync(filePath, 'utf8')

  assert.match(source, /getRealtimeStats\(\)/)
  assert.match(source, /setInterval\(fetchRealtimeStats,\s*5000\)/)
  assert.match(source, /closest\('\.drag-handle'\)/)
  assert.match(source, /strokeDasharray=\{`\$\{activeArcLength\} \$\{ringCircumference\}`\}/)
  assert.match(source, /strokeDasharray=\{`\$\{trackArcLength\} \$\{ringCircumference\}`\}/)
  assert.match(source, /strokeDasharray=\{`\$\{memoryActiveArcLength\} \$\{ringCircumference\}`\}/)
  assert.match(source, /strokeDashoffset=\{-18\}/)
  assert.match(source, /rotate-\[-78deg\]/)
  assert.match(source, /group-hover\/trigger:rotate-\[-70deg\]/)
  assert.doesNotMatch(source, /CPU \{cpuLoad\}%/)
  assert.doesNotMatch(source, /RAM \{memoryUsage\}%/)
  assert.doesNotMatch(source, /-bottom-8/)
})

test('FileDropover peeks when docked on hover and restores dock on hover-out', () => {
  const filePath = path.join(__dirname, 'FileDropover.tsx')
  const source = fs.readFileSync(filePath, 'utf8')

  assert.match(source, /electron\.floatBall\.peek\(\)/)
  assert.match(source, /electron\.floatBall\.restoreDock\(\)/)
  assert.match(source, /!isDraggingRef\.current/)
  assert.match(source, /!isExpanded/)
  assert.match(source, /setDockState\('peek'\)/)
  assert.match(source, /setDockState\('docked'\)/)
})

test('FileDropover opens the stash panel only on double-click or context menu, not single-click', () => {
  const filePath = path.join(__dirname, 'FileDropover.tsx')
  const source = fs.readFileSync(filePath, 'utf8')

  assert.match(source, /const openExpandedPanel =/)
  assert.match(source, /setIsExpanded\(true\)/)
  assert.match(source, /onDoubleClick=\{openExpandedPanel\}/)
  assert.match(source, /onContextMenu=\{openExpandedPanel\}/)
  assert.doesNotMatch(source, /onClick=\{\(e\) => \{\s*e\.preventDefault\(\)\s*e\.stopPropagation\(\)\s*setIsExpanded\(true\)\s*\}\}/)
})
