const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const script = fs.readFileSync(path.join(__dirname, 'script.js'), 'utf8')
const style = fs.readFileSync(path.join(__dirname, 'style.css'), 'utf8')

test('hero cards map to tool groups and scroll timing comes only from toolsSection', () => {
  const flightTargetsBlock = script.match(/const flightTargets = \{[\s\S]*?\n  \}/)
  const dockTargetsBlock = script.match(/const dockTargets = \{[\s\S]*?\n  \}/)
  const heroTargetsBlock = script.match(/const heroTargets = \{[\s\S]*?\n  \}/)
  const scheduleSyncBlock = script.match(/const scheduleSync = \(\) => \{[\s\S]*?\n  \}/)
  const syncScrollStateBlock = script.match(/const syncScrollState = \(\) => \{[\s\S]*?\n  \}/)
  const syncFlightTargetsBlock = script.match(/const syncFlightTargets = \(\) => \{[\s\S]*?\n  \}/)
  const viewportProgressBlock = script.match(/const getViewportProgress = \(element, startRatio, endRatio\) => \{[\s\S]*?\n  \}/)

  assert.ok(flightTargetsBlock, 'expected flightTargets block in script.js')
  assert.ok(dockTargetsBlock, 'expected dockTargets block in script.js')
  assert.ok(heroTargetsBlock, 'expected heroTargets block in script.js')
  assert.ok(scheduleSyncBlock, 'expected scheduleSync block in script.js')
  assert.ok(syncScrollStateBlock, 'expected syncScrollState block in script.js')
  assert.ok(syncFlightTargetsBlock, 'expected syncFlightTargets block in script.js')
  assert.ok(viewportProgressBlock, 'expected getViewportProgress block in script.js')

  assert.match(flightTargetsBlock[0], /\bcapture:\s*document\.querySelector\('\[data-flight-target="capture"\]'\)/)
  assert.match(flightTargetsBlock[0], /\borganize:\s*document\.querySelector\('\[data-flight-target="organize"\]'\)/)
  assert.match(flightTargetsBlock[0], /\butility:\s*document\.querySelector\('\[data-flight-target="utility"\]'\)/)
  assert.doesNotMatch(flightTargetsBlock[0], /clipboard/)
  assert.doesNotMatch(flightTargetsBlock[0], /matrix/)

  assert.match(dockTargetsBlock[0], /\bcapture:\s*document\.querySelector\('\[data-flight-dock="capture"\]'\)/)
  assert.match(dockTargetsBlock[0], /\borganize:\s*document\.querySelector\('\[data-flight-dock="organize"\]'\)/)
  assert.match(dockTargetsBlock[0], /\butility:\s*document\.querySelector\('\[data-flight-dock="utility"\]'\)/)
  assert.doesNotMatch(dockTargetsBlock[0], /clipboard/)
  assert.doesNotMatch(dockTargetsBlock[0], /matrix/)

  assert.match(syncFlightTargetsBlock[0], /const targetMap = \{[\s\S]*capture:\s*'capture'[\s\S]*organize:\s*'organize'[\s\S]*clipboard:\s*'organize'[\s\S]*utility:\s*'utility'[\s\S]*matrix:\s*'capture'[\s\S]*\}/)
  assert.match(syncFlightTargetsBlock[0], /const dockTarget = dockTargets\[targetKey\]/)
  assert.match(syncFlightTargetsBlock[0], /const dockRect = dockTarget\?\.getBoundingClientRect\(\)/)
  assert.match(syncFlightTargetsBlock[0], /const dockX = dockRect \?[\s\S]*: targetX/)
  assert.match(syncFlightTargetsBlock[0], /const dockY = dockRect \?[\s\S]*: targetY/)
  assert.match(syncFlightTargetsBlock[0], /const dockScale = dockRect \? dockRect\.width \/ card\.offsetWidth : 1/)
  assert.match(syncFlightTargetsBlock[0], /card\.style\.setProperty\('--dock-x',/)
  assert.match(syncFlightTargetsBlock[0], /card\.style\.setProperty\('--dock-y',/)
  assert.match(syncFlightTargetsBlock[0], /card\.style\.setProperty\('--dock-scale',/)

  assert.doesNotMatch(script, /document\.querySelector\('#scenarios'\)/)
  assert.doesNotMatch(script, /document\.querySelector\('#system'\)/)
  assert.doesNotMatch(syncScrollStateBlock[0], /getViewportProgress\(scenariosSection/)
  assert.match(syncScrollStateBlock[0], /travelProgress:\s*getViewportProgress\(toolsSection, 1\.1, 0\.34\)/)
  assert.match(syncScrollStateBlock[0], /morphProgress:\s*getViewportProgress\(toolsSection, 0\.74, 0\.2\)/)
  assert.match(syncScrollStateBlock[0], /dockProgress:\s*getViewportProgress\(toolsSection, 0\.46, 0\.08\)/)
  assert.match(syncScrollStateBlock[0], /settleProgress:\s*getViewportProgress\(toolsSection, 0\.92, 0\.14\)/)
  assert.match(heroTargetsBlock[0], /capture:\s*flightTargets\.capture/)
  assert.match(heroTargetsBlock[0], /clipboard:\s*flightTargets\.organize/)
  assert.match(heroTargetsBlock[0], /matrix:\s*flightTargets\.capture/)
  assert.match(syncScrollStateBlock[0], /clipboard:\s*easeOutCubic\(getViewportProgress\(heroTargets\.clipboard, 0\.82, 0\.22\)\)/)
  assert.match(syncScrollStateBlock[0], /matrix:\s*easeOutCubic\(getViewportProgress\(heroTargets\.matrix, 0\.72, 0\.18\)\)/)
  assert.doesNotMatch(syncScrollStateBlock[0], /travelLead/)
  assert.doesNotMatch(syncScrollStateBlock[0], /travelFollow/)

  assert.match(scheduleSyncBlock[0], /window\.requestAnimationFrame\(\(\) => \{/)
  assert.match(syncScrollStateBlock[0], /--flight-morph/)
  assert.match(syncScrollStateBlock[0], /--flight-dock/)
})

test('hero sticky keeps the dock handoff style contract', () => {
  const heroStickyRule = style.match(/\.hero-sticky\s*\{[\s\S]*?\n\}/)

  assert.ok(heroStickyRule, 'expected .hero-sticky rule in style.css')
  assert.match(style, /--dock-x/)
  assert.match(style, /--dock-y/)
  assert.match(style, /--dock-scale/)
  assert.match(style, /--clipboard-highlight/)
  assert.match(heroStickyRule[0], /overflow:\s*visible/)
  assert.match(style, /var\(--flight-dock-soft\)/)
  assert.match(style, /\.hero-flight-card\[data-flight-card=/)
})

test('hero title uses launch-page typography instead of the old stacked tower', () => {
  assert.match(style, /\.hero-title\s*{/)
  assert.match(style, /\.hero-title-line-wide\s*{/)
  assert.match(style, /max-width:\s*10ch/)
  assert.match(style, /font-size:\s*clamp\(3\.4rem,\s*6\.2vw,\s*6\.4rem\)/)
  assert.match(style, /letter-spacing:\s*-0\.07em/)
})
